dataset:
  type: face_colored_mesh
  name: face_colored_mesh
  # distribtuion parameters
  color: laplacian_eigen_function
  k_eigen_value: 50
  # surface parameters
  checkpoint: eikonal/exps/bunny/2021_05_20_16_27_01/network_100000.pth
  sdf_params:
    latent_size: 0
    d_in: 3
    d_out: 1
    dims: [512, 512, 512] #, 512, 512, 512, 512, 512]
    skip_in: [] #[4]
    weight_norm: false
    geometric_init: true
    bias: 1.0
  mesh_n_grid_points: 100
  # general parameters
  input_dim: 3
  training_size: 500000
  validation_size: 50000
  test_size: 50000

model:
  manifold: implicit
  pde_type: divergence
  architectures:
    potential:
      type: mlp
      hidden_dims: [512, 512, 512, 512, 512, 512]
      activation: softplus100
  # ode solver
  ode_args:
    method: dopri5
    atol: 0.00001
    rtol: 0.00001

optim:
  batch_size: 10000
  mc_batch_size_scale: 1
  eval_batch_size: 10000
  weight_decay: 0
  lr_initial: 0.0001
  lr_gamma: 0.1
  max_epochs: 1000
  eval_every: 100
  lambda_plus: 1
  lambda_minus: 1

early_stop:
  patience: 100000

logger: 
  - tensorboard
  - file
